DROP PROCEDURE IF EXISTS CheckUserRegister
GO
CREATE PROCEDURE CheckUserRegister
(
	@EMAIL NVARCHAR(MAX),
	@USER_ID NVARCHAR (100),
	@ISVALID BIT OUT
)
AS
BEGIN
SET @ISVALID = (SELECT COUNT(1) FROM ACC_USER WHERE (EMAIL = @EMAIL OR USER_ID = @USER_ID) AND SYNCOPERATION<>'D')
END
GO
