DROP PROCEDURE IF EXISTS [dbo].[RegisterUser]
GO
CREATE PROCEDURE RegisterUser
(
	@EMAIL NVARCHAR(MAX),
	@USER_ID NVARCHAR(100),
	@PASSWORD NVARCHAR(100),
	@ROLES INT
)
AS
BEGIN
	INSERT INTO ACC_USER
	VALUES
	(@USER_ID, @PASSWORD, @EMAIL, @ROLES, GETDATE(), 'A',GETDATE())
END
GO
