IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'ACC_USER' AND xtype = 'U')
CREATE TABLE 
ACC_USER
(
	USER_ID NVARCHAR(100) NOT NULL,
	PASSWORD NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(MAX) NOT NULL,
	ROLES NVARCHAR(50) NOT NULL,
	CREATED_DT DATETIME NOT NULL,
	CREATED_BY NVARCHAR(100) NOT NULL,
	SYNCOPERATION CHAR(1) NOT NULL,
	SYNCVERSION DATETIME NOT NULL,
	PRIMARY KEY (USER_ID)
)
GO


IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'COURSE' AND xtype = 'U')
CREATE TABLE
COURSE 
(	
	COURSE_ID NVARCHAR(5) NOT NULL,
	COURSE_NAME NVARCHAR(200) NOT NULL,
	FACULTY NVARCHAR(200) NOT NULL,
	COURSE_DESC NVARCHAR(MAX) NULL,
	EXPIRTY_DT DATETIME NOT NULL,
	CREATED_DT DATETIME NOT NULL,
	CREATED_BY NVARCHAR(200) NOT NULL,
	APPROVE_DT DATETIME NULL,
	STATUS NVARCHAR(20) NOT NULL,
	SYNCVERSION DATETIME NOT NULL,
	SYNCOPERATION CHAR(1) NOT NULL,
	PRIMARY KEY (COURSE_ID),
)


IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'SYS_DESCRIPTION' AND xtype = 'U')
CREATE TABLE
SYS_DESCRIPTION
(
	TABLE_NAME NVARCHAR(100) NOT NULL,
	TABLE_FIELD NVARCHAR(100) NOT NULL,
	SYNCOPERATION CHAR(1) NOT NULL,
	SYNCVERSION DATETIME NOT NULL
)


--IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'COURSE_DOCS' AND xtype = 'U')
--CREATE TABLE
--COURSE

